### ISSUE TITLE
No dir "gen" under ./www/js

### ISSUE THREAD

**Issue by baiyuxiong** [quintans/taskboard#1]
These js files cannot found:
js/gen/toolkit.js
js/gen/infra.js
js/gen/app.js
js/gen/controllers.js

Error msgs in chrome console:
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9090/js/gen/controllers.js Failed to load resource: the server responded with a status of 404 (Not Found)
angular.min.js:29 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.3/$injector/modulerr?p0=taskboard&p1=Error%….c%20(http%3A%2F%2Flocalhost%3A9090%2Fjs%2Flib%2Fangular.min.js%3A17%3A315)
angular.min.js.map:1 GET http://localhost:9090/js/lib/angular.min.js.map 404 (Not Found)
angular-route.min.js.map:1 GET http://localhost:9090/js/lib/angular-route.min.js.map 404 (Not Found)
toastr.min.js.map:1 GET http://localhost:9090/js/lib/toastr.min.js.map 404 (Not Found)

**Comment by quintans** [comment]
They are now included. Try again please.
