### ISSUE TITLE
 Field 'DEAD' doesn't have a default value

### ISSUE THREAD

**Issue by morphium** [quintans/taskboard#3]
Now I am stuck at new user creation (in web ui via Manage Users page).

Every time I try to create a new user, I merely see this error poping out:

Server Error
undefined: Error 1364: Field 'DEAD' doesn't have a default value SQL: INSERT INTO `USER`(`VERSION`, `NAME`, `USERNAME`, `PASSWORD`, `CREATION`, `USER_CREATION`) VALUES(?, ?, ?, ?, ?, ?) Parameters: [1 0xc4201229e0 0xc4201229f0 0xc420212a00 2017/03/13-01:20:03 1]

I'll fork and try to fix. What's DEAD though?

**Comment by quintans** [comment]
Remove the column DEAD from the table creation script, please. I will fix the SQL script as soon as possible.

**Comment by quintans** [comment]
Fixed the SQL scripts.

**Comment by morphium** [comment]
Thanks, it worked for me too. Now I don't seem to be able to edit created tasks... but it's a new issue :)

**Comment by quintans** [comment]
That issue revealed an unintended behaviour (not a bug ;)) in goSQL. If you update goSQL you will be able to edit.
